{
 "title": "3 - PowerFlex - Storage Pools",
 "tags": [ "PowerFlex" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CLU",
    "label": "Cluster",
    "query": {
     "query": "label_values(storagepool_num_devices, clu_name)"
    }
   },
   {
    "name": "DOMAIN",
    "label": "Protection Domain",
    "query": {
     "query": "label_values(storagepool_num_devices{clu_name=\"$CLU\"}, pdo_name)"
    }
   },
   {
    "name": "POOL",
    "label": "Storage Pool",
    "query": {
     "query": "label_values(storagepool_num_devices{clu_name=\"$CLU\", pdo_name=\"$DOMAIN\"}, sto_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "storagepool_capacity_use_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}"
    }
   ]
  },
  {
   "title": "Storage Pool capacities",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "storagepool_capacity_failed_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}",
     "legendFormat": "failed"
    },
    {
     "expr": "storagepool_capacity_moving_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}",
     "legendFormat": "moving"
    },
    {
     "expr": "storagepool_capacity_protected_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}",
     "legendFormat": "protected"
    },
    {
     "expr": "storagepool_capacity_spare_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}",
     "legendFormat": "spare"
    },
    {
     "expr": "storagepool_capacity_unused_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}",
     "legendFormat": "unused"
    },
    {
     "expr": "storagepool_capacity_use_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}",
     "legendFormat": "use"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "storagepool_capacity_available_volume_allocation_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}"
    }
   ]
  },
  {
   "title": "Read Op/s",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storagepool_read_total_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}"
    }
   ]
  },
  {
   "title": "Write Op/s",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "storagepool_write_total_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}"
    }
   ]
  },
  {
   "title": "Read MB/s",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "storagepool_read_total_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}"
    }
   ]
  },
  {
   "title": "Write MB/s",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "storagepool_write_total_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "storagepool_read_total_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}",
     "legendFormat": "Read ops"
    },
    {
     "expr": "storagepool_write_total_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}",
     "legendFormat": "Write ops"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "storagepool_read_total_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}",
     "legendFormat": "Read bw"
    },
    {
     "expr": "storagepool_write_total_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}",
     "legendFormat": "Write bw"
    }
   ]
  },
  {
   "title": "Top 10 Volume read op/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "topk(10, avg(volume_read_user_data_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}) BY (vol_name))",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Volume write op/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "topk(10, avg(volume_write_user_data_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}) BY (vol_name))",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Volume read bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "topk(10, avg(volume_read_user_data_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}) BY (vol_name))",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Volume write bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "topk(10, avg(volume_write_user_data_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}) BY (vol_name))",
     "legendFormat": "{{vol_name}}"
    }
   ]
  },
  {
   "title": "Top 10 SDS read op/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "topk(10, avg(sds_read_total_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\"}) BY (sds_name))",
     "legendFormat": "{{sds_name}}"
    }
   ]
  },
  {
   "title": "Top 10 SDS write op/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "topk(10, avg(sds_write_total_iops{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\"}) BY (sds_name))",
     "legendFormat": "{{sds_name}}"
    }
   ]
  },
  {
   "title": "Top 10 SDS read bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "topk(10, avg(sds_read_total_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\"}) BY (sds_name))",
     "legendFormat": "{{sds_name}}"
    }
   ]
  },
  {
   "title": "Top 10 SDS write bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "topk(10, avg(sds_write_total_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\"}) BY (sds_name))",
     "legendFormat": "{{sds_name}}"
    }
   ]
  },
  {
   "title": "Max Pool's read latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(device_read_latency_ms{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}) by (sds_name)",
     "legendFormat": "{{sds_name}}"
    }
   ]
  },
  {
   "title": "Max Pool's write latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(device_write_latency_ms{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sto_name=\"$POOL\"}) by (sds_name)",
     "legendFormat": "{{sds_name}}"
    }
   ]
  }
 ]
}