{
 "title": "5 - PowerFlex - SDC",
 "tags": [ "PowerFlex" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CLU",
    "query": {
     "query": "label_values(sdc_write_user_data_iops, clu_name)"
    }
   },
   {
    "name": "SDC",
    "query": {
     "query": "label_values(sdc_write_user_data_iops{clu_name=\"$CLU\"}, sdc_name)"
    }
   },
   {
    "name": "SDC_ID",
    "query": {
     "query": "label_values(sdc_write_user_data_iops{clu_name=\"$CLU\", sdc_name=\"$SDC\"}, sdc_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Read Op/s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sdc_read_user_data_iops{sdc_id=\"$SDC_ID\"}"
    }
   ]
  },
  {
   "title": "Write Op/s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sdc_write_user_data_iops{sdc_id=\"$SDC_ID\"}"
    }
   ]
  },
  {
   "title": "Mapped volume(s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sdc_mapped_volumes{sdc_id=\"$SDC_ID\"}"
    }
   ]
  },
  {
   "title": "Read MB/s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sdc_read_user_data_kb{sdc_id=\"$SDC_ID\"}"
    }
   ]
  },
  {
   "title": "Write MB/s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sdc_write_user_data_kb{sdc_id=\"$SDC_ID\"}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sdc_read_user_data_iops{sdc_id=\"$SDC_ID\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "sdc_write_user_data_iops{sdc_id=\"$SDC_ID\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sdc_read_user_data_kb{sdc_id=\"$SDC_ID\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "sdc_write_user_data_kb{sdc_id=\"$SDC_ID\"}",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}