{
 "title": "1 - PowerFlex - Cluster",
 "tags": [ "sio" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CLU",
    "query": {
     "query": "label_values(system_num_sds, clu_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h2><b>Cluster statistics</b> : $CLU</h2></center>"
   }
  },
  {
   "title": "Read Op/s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_read_total_iops{clu_name=\"$CLU\"}"
    }
   ]
  },
  {
   "title": "Write Op/s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_write_total_iops{clu_name=\"$CLU\"}"
    }
   ]
  },
  {
   "title": "Read Mb/s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_read_total_kb{clu_name=\"$CLU\"}"
    }
   ]
  },
  {
   "title": "Write Mb/s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_write_total_kb{clu_name=\"$CLU\"}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "system_read_total_iops{clu_name=\"$CLU\"}",
     "legendFormat": "R"
    },
    {
     "expr": "system_write_total_iops{clu_name=\"$CLU\"}",
     "legendFormat": "W"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "system_read_total_kb{clu_name=\"$CLU\"}",
     "legendFormat": "R"
    },
    {
     "expr": "system_write_total_kb{clu_name=\"$CLU\"}",
     "legendFormat": "W"
    }
   ]
  },
  {
   "title": "Sdc's read op/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "topk(10, avg(sdc_read_user_data_iops{clu_name=\"$CLU\"}) BY (sdc_name))",
     "legendFormat": "{{sdc_name}}"
    }
   ]
  },
  {
   "title": "Sdc's write op/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "topk(10, avg(sdc_write_user_data_iops{clu_name=\"$CLU\"}) BY (sdc_name))",
     "legendFormat": "{{sdc_name}}"
    }
   ]
  },
  {
   "title": "Sdc's read bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "topk(10, avg(sdc_read_user_data_kb{clu_name=\"$CLU\"}) BY (sdc_name))",
     "legendFormat": "{{sdc_name}}"
    }
   ]
  },
  {
   "title": "Sdc's write bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "topk(10, avg(sdc_write_user_data_kb{clu_name=\"$CLU\"}) BY (sdc_name))",
     "legendFormat": "{{sdc_name}}"
    }
   ]
  },
  {
   "title": "Max Pool's read latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(device_read_latency_ms{clu_name=\"$CLU\"}) by (sto_name,pdo_name)",
     "legendFormat": "{{pdo_name}} / {{sto_name}}"
    }
   ]
  },
  {
   "title": "Max Pool's write latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(device_write_latency_ms{clu_name=\"$CLU\"}) by (sto_name,pdo_name)",
     "legendFormat": "{{pdo_name}} / {{sto_name}}"
    }
   ]
  },
  {
   "title": "Forward Rebuild IOPs/Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "system_read_fwd_rebuild_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Read ops"
    },
    {
     "expr": "system_write_fwd_rebuild_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Write ops"
    },
    {
     "expr": "system_read_fwd_rebuild_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Read bw"
    },
    {
     "expr": "system_write_fwd_rebuild_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Write bw"
    }
   ]
  },
  {
   "title": "Backward Rebuild IOPs/Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "system_read_bck_rebuild_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Read ops"
    },
    {
     "expr": "system_write_bck_rebuild_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Write ops"
    },
    {
     "expr": "system_read_bck_rebuild_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Read bw"
    },
    {
     "expr": "system_write_bck_rebuild_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Write bw"
    }
   ]
  },
  {
   "title": "Rebalance IOPs/Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "system_read_rebalance_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Read ops"
    },
    {
     "expr": "system_write_rebalance_iops{clu_name=\"$CLU\"}",
     "legendFormat": "Write ops"
    },
    {
     "expr": "system_read_rebalance_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Read bw"
    },
    {
     "expr": "system_write_rebalance_kb{clu_name=\"$CLU\"}",
     "legendFormat": "Write bw"
    }
   ]
  }
 ]
}