{
 "title": "0 - PowerFlex - Global",
 "tags": [ "sio" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "System IOPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(system_read_total_iops + system_write_total_iops) BY (clu_name)",
     "legendFormat": "{{clu_name}}"
    }
   ]
  },
  {
   "title": "System Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(system_read_total_kb + system_write_total_kb) BY (clu_name)",
     "legendFormat": "{{clu_name}}"
    }
   ]
  },
  {
   "title": "Top 15 StoragePool IOPS",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(15,max(storagepool_read_total_iops + storagepool_write_total_iops) by (clu_name,pdo_name,sto_name))",
     "legendFormat": "{{clu_name}} / {{pdo_name}} / {{sto_name}}"
    }
   ]
  },
  {
   "title": "Top 15 StoragePool Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "topk(15,max(storagepool_read_total_kb + storagepool_write_total_kb) by (clu_name,pdo_name,sto_name))",
     "legendFormat": "{{clu_name}} / {{pdo_name}} / {{sto_name}}"
    }
   ]
  },
  {
   "title": "Top 15 Volume IOPS",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(15,max(volume_read_user_data_iops + volume_write_user_data_iops) by (clu_name,pdo_name,sto_name,vol_name))",
     "legendFormat": "{{clu_name}} / {{pdo_name}} / {{sto_name}} / {{vol_name}}"
    }
   ]
  },
  {
   "title": "Top 15 Volume Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "topk(15,max(volume_read_user_data_kb + volume_write_user_data_kb) by (clu_name,pdo_name,sto_name,vol_name))",
     "legendFormat": "{{clu_name}} / {{pdo_name}} / {{sto_name}} / {{vol_name}}"
    }
   ]
  },
  {
   "title": "Top 15 Disks read latencies",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(15,max(device_read_latency_ms) by (clu_name,pdo_name,sto_name,dev_name))",
     "legendFormat": "{{clu_name}} / {{pdo_name}} / {{sto_name}} / {{dev_name}}"
    }
   ]
  },
  {
   "title": "Top 15 Disks write latencies",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(15,max(device_write_latency_ms) by (clu_name,pdo_name,sto_name,dev_name))",
     "legendFormat": "{{clu_name}} / {{pdo_name}} / {{sto_name}} / {{dev_name}}"
    }
   ]
  }
 ]
}