{
 "title": "2 - PowerFlex - SDS",
 "tags": [ "sio" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CLU",
    "label": "Cluster",
    "query": {
     "query": "label_values(storagepool_num_devices, clu_name)"
    }
   },
   {
    "name": "DOMAIN",
    "label": "Protection Domain",
    "query": {
     "query": "label_values(storagepool_num_devices{clu_name=\"$CLU\"}, pdo_name)"
    }
   },
   {
    "name": "POOL",
    "label": "Storage Pool",
    "query": {
     "query": "label_values(storagepool_num_devices{clu_name=\"$CLU\", pdo_name=\"$DOMAIN\"}, sto_name)"
    }
   },
   {
    "name": "POOL_ID",
    "query": {
     "query": "label_values(storagepool_num_devices{clu_name=\"$CLU\", pdo_name=\"$DOMAIN\", sto_name=\"$POOL\"}, sto_id)"
    }
   },
   {
    "name": "SDS",
    "query": {
     "query": "label_values(device_read_size_bytes{clu_name=\"$CLU\", pdo_name=\"$DOMAIN\", sto_id=\"$POOL_ID\"}, sds_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Read Op/s",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sds_read_total_iops{sds_name=\"$SDS\"})"
    }
   ]
  },
  {
   "title": "Write Op/s",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sds_write_total_iops{sds_name=\"$SDS\"})"
    }
   ]
  },
  {
   "title": "Read MB/s",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sds_read_total_kb{sds_name=\"$SDS\"})"
    }
   ]
  },
  {
   "title": "Write MB/s",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sds_write_total_kb{sds_name=\"$SDS\"})"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sds_read_total_iops{sds_name=\"$SDS\"}",
     "legendFormat": "Read ops"
    },
    {
     "expr": "sds_write_total_iops{sds_name=\"$SDS\"}",
     "legendFormat": "Write ops"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sds_read_total_kb{sds_name=\"$SDS\"}",
     "legendFormat": "Read ops"
    },
    {
     "expr": "sds_write_total_kb{sds_name=\"$SDS\"}",
     "legendFormat": "Write ops"
    }
   ]
  },
  {
   "title": "Disks read latencies",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(device_read_latency_ms{sds_name=\"$SDS\"}) by (dev_name)",
     "legendFormat": "{{dev_name}}"
    }
   ]
  },
  {
   "title": "Disks write latencies",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(device_write_latency_ms{sds_name=\"$SDS\"}) by (dev_name)",
     "legendFormat": "{{dev_name}}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sds_capacity_use_kb{clu_name=\"$CLU\",pdo_name=\"$DOMAIN\",sds_name=\"$SDS\"}",
     "legendFormat": "{{sds_name}}"
    }
   ]
  }
 ]
}